### ISSUE TITLE
Characters

### ISSUE THREAD

**Issue by glcryxdays** [blackjackkent/RPThreadTrackerV3.FrontEnd#38] opened 2018-08-14 14:58 UTC
At first I thought it was just me adding the same character a couple of times because I'd forgotten I'd already done it, but I've noticed lately that there's names that are repeating themselves even when I know there was only one the last time I've checked. I've added other names in the mean time, and I think it might be a result of that. 
Overall what I'm saying, is that I think when you add a new character, it adds it, but also duplicates a preexisting one too.

**Comment by blackjackkent** [comment] 2018-08-14 15:31
That's...very strange. O.o I can't reproduce this issue; could you shoot me your account username (here or by email if you'd prefer) so I can look in the database and see what the situation is there?

**Comment by glcryxdays** [comment] 2018-08-14 15:44
It's glcryxdays and unfortunately I've gotten rid of a lot of them but there's still one instance of it (name is Jorie). Like I said, it's not the first time but I thought it was my own fault at first, but then this happened today.

**Comment by blackjackkent** [comment] 2018-08-14 17:00
Hm. Does this happen every time you create a character?

**Comment by glcryxdays** [comment] 2018-08-15 07:33
Usually, but not always right away. I've just added some more characters, but maybe I should just email you next time it happens? I feel like it might just be me or something.

**Comment by blackjackkent** [comment] 2018-08-15 15:06
Hm. Yeah, I definitely want to look into this further because no code behavior comes from nowhere. :D When you next encounter it, please email me about the exact process you went through/what you were doing just before the duplicate appeared. :)

**Comment by blackjackkent** [comment] 2018-08-22 18:21
Closing this for now but feel free to reopen or email me with further info. :) Thank you!

**Closed as completed by blackjackkent** 2018-08-22 18:21 UTC
