### ISSUE TITLE
Error when creating thread without changing default selected character

### ISSUE THREAD

**Issue by minixmousy** [blackjackkent/RPThreadTrackerV3.FrontEnd#3] opened 2018-07-10 01:39 UTC
user: minniemouse

attempting to track new thread.
apply character, title, post number, partner url, and a single tag (both with and without non-alphanumeric characters in the tag).

receive the error: there was a problem updating your thread.
thread is not tracked.

**Comment by minixmousy** [comment] 2018-07-10 01:39
i receive the same error when putting only the thread title and post number

**Comment by minixmousy** [comment] 2018-07-10 01:40
receive the same error when removing non-alphanumeric symbols from title

**Comment by minixmousy** [comment] 2018-07-10 01:40
error is alleviated when i have more than one "character"

**Comment by minixmousy** [comment] 2018-07-10 01:42
problem persists even with more than one character unless i navigate from the default character to another one and then back.

**Comment by blackjackkent** [comment] 2018-07-10 04:21
Gotcha -- OK I think I know what the problem is here. Thank you! Will let you know when I've put in a fix. :)

**Comment by blackjackkent** [comment] 2018-07-10 17:46
Hmm. On closer inspection, I'm unable to replicate this issue; I'm able to create a thread on my account without changing the default selected character in the modal. 🤔

Could you provide me with a screenshot of the exact information you're using to submit the thread when it fails? Thanks!

**Comment by minixmousy** [comment] 2018-07-10 18:20
Yeah can do!

**Comment by minixmousy** [comment] 2018-07-10 18:22
except that it now works straight off the bat!! lol

**Comment by blackjackkent** [comment] 2018-07-10 18:24
Hmm. Well, that's weird. :P I'm going to go ahead and close this issue since it's now working for both of us but if you encounter the issue again please let me know and I'll look into it further. Thanks! :)

**Closed as completed by blackjackkent** 2018-07-10 18:24 UTC
