### ISSUE TITLE
Visual Fix: Thread tables too large for laptop screen (1366*768)

### ISSUE THREAD

**Issue by Maxstiel** [blackjackkent/RPThreadTrackerV3.FrontEnd#31] opened 2018-07-23 16:07 UTC
Hello there. 
I imagine it wasn't supposed to act this way, however the tables for the threads (in All Thread, Your Turn, Their Turn, Archived and Queued) is too large for laptop screens. With that issue it's not possible to see what partner is tracked. Here's a photo to show what I am talking about:
![image](https://user-images.githubusercontent.com/41587095/43088681-0b68294c-8ea3-11e8-8c10-8a7f6ca1ab32.png)

**Comment by blackjackkent** [comment] 2018-07-23 16:12
Hey! Thanks for getting in touch. :) I'm not sure I understand the issue you're reporting. It looks as if you were able to scroll the table horizontally as intended, to see the Tracked Partner column. What information are you not able to see that you're expecting?

**Comment by Maxstiel** [comment] 2018-07-23 16:17
I wasn't certain the scroll was intended, apologies for this. 
The thing is, being part of a multi-fandom group, I tend to sort the threads per watched short name to make sure I do not bubble with anyone, or to archive the threads that are over when people leave. Scrolling from side to side makes the process a bit harder as I do have to scroll back and forth to check what urls correspond to what thread.

**Comment by blackjackkent** [comment] 2018-07-23 16:35
Hmm. Unfortunately at that screen size there's always going to be some info that doesn't fit on the screen and needs to be scrolled to, and different people have different needs for which columns should be in view initially. I do plan to add a feature soon after V3 is released to allow users to customize what order the columns appear in the table; would that address the issue you're describing?

**Comment by Maxstiel** [comment] 2018-07-24 10:37
I understand that, yes. 
It would definitely address that issue, and that would be amazing to do so, yes!

**Comment by blackjackkent** [comment] 2018-07-24 15:06
Cool! I will close this ticket, then, and move that feature development up the priority list for after V3 is released. :) Thanks so much for the feedback!

**Closed as completed by blackjackkent** 2018-07-24 15:06 UTC
