### ISSUE TITLE
Public Views error

### ISSUE THREAD

**Issue by fibifibita** [blackjackkent/RPThreadTrackerV3.FrontEnd#32] opened 2018-07-27 15:31 UTC
Hey! When trying to create a public view during the first attempt I get the red box stating there's been a problem (but not which problem). When I try it for a 2nd time it works just fine. Not sure if it's a problem with my connection or that it doesn't take the items the first time but maybe the error could state what's wrong?
(I don't think anything is wrong cos the 2nd time I do it,I choose the exact same things so it's probably a latency issue but just in case!)

**Comment by blackjackkent** [comment] 2018-07-27 16:44
Hmm, that's very weird. I can't reproduce it on my end; does it always happen the first time you try to create a public view after loading the page? Or was it only the one time?

**Comment by blackjackkent** [comment] 2018-08-03 14:59
Haven't had any further response so I'm closing this ticket. :) Feel free to reopen it if you have more info though!

**Closed as completed** 2018-08-03 15:00 UTC
