### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by myricds** [blackjackkent/RPThreadTrackerV3.FrontEnd#43] opened 2018-09-18 04:38 UTC
Not so much an "issue" per se as it is an annoyance. The buttons - whether the "Track New Thread" or "Edit Thread" etc. seem to be extremely particular about where they're clicked. Meaning, one might expect clicking anywhere on a button to activate it, but it seems to require clicking in the center of the button for best results. I would like to add that I'm not sure if this has something to do with the new Chrome update, as I have not tested it on other browsers.

**Comment by blackjackkent** [comment] 2018-09-24 16:12
Good catch -- I see what the issue is here I think. Should be an easy fix; I'll let you know when I've tweaked it. (Sorry for the delay in responding; I've been out of town.)

**Comment by blackjackkent** [comment] 2018-09-25 15:05
Hey -- this issue should be fixed now! Let me know if you're still running into the problem. :) Thank you for reporting it! :)

**Closed as completed** 2018-10-01 15:27 UTC
